# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gauncioul
email: guancioul@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Empowering Curiosity, Inspiring Discovery: Your Gateway to a World of Knowledge
  Welcome to our digital realm, where curiosity knows no bounds, and discovery is the ultimate thrill. Unveil the secrets of the universe, unravel the mysteries of technology, explore the depths of human wisdom, and embark on a journey of learning and enlightenment.
  Our website is your trusted guide through the endless corridors of knowledge. With a diverse array of articles, resources, and insights, we are your go-to destination for expanding your horizons. Whether you're a seasoned scholar or a passionate learner, our content will ignite your curiosity and fuel your pursuit of wisdom.
  Join our community of inquisitive minds as we delve into the fascinating realms of science, technology, culture, and beyond. Our mission is simple: to empower you with the information you need to navigate the complexities of our world and inspire you to become a lifelong explorer.
  Get ready to embark on a transformative journey of discovery. Welcome to a world where knowledge knows no limits, and every click opens a door to a new adventure.
twitter_username: username
github_username: guancioul
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: guancioul/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Taipei # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Guancioul"
  avatar : "/assets/images/personal-photo200.jpg"
  bio    : "Exploring New Knowledge and Verifying Information Through Research and Practice"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://guancioul.github.io"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/guancioul"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/guancioul"
    # - label: "HackerRank"
    #   icon: "fab fa-fw fa-hackerrank"
    #   url: "https://www.hackerrank.com/guancioul"
    # - label: "Leetcode"
    #   icon: "fab fa-fw fa-code"
    #   url: "https://leetcode.com/guancioul"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/guancioul"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/guancioul"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
